### ISSUE TITLE
Characters not displayed correctly

### ISSUE THREAD

**Issue by bjorn** [mana/mana#43]
Some error boxes are showing instead of my characters. Probably the result of Mana client missing some feature that was added to ManaPlus.

![image](https://github.com/mana/mana/assets/531764/ab71cdff-5d62-4c46-aa0f-c4507a496f12)

**Comment by pazkero** [comment]
The currency symbol is because units.xml was introduced.

So I assume the error box might be because paths.xml ? Or worse ─ TmwAthena is now putting all items in subfiles (making a nesting mess). 

I don't think Mana supports `<include>` tag. Once you're in, if all players are error boxes and all monsters work then it is that missing tag (I unified monsters.xml back not long ago, but AFAIK there are no plans to unify items.xml back, and HoraK wanted to split monsters.xml again, not sure if they already did that or not).

**Comment by bjorn** [comment]
> I don't think Mana supports `<include>` tag.

Hmm, actually the Mana client supported `<include>` before ManaPlus, in all supported data files, with change bd1fdd87eed48ba3ffcc413936d6a6a60a429a97. Whereas ManaPlus started supporting this in each file separately later in the same month, first with `items.xml` in change [`61e3fa8513c1`](https://git.themanaworld.org/mana/plus/-/commit/61e3fa8513c1bc2644348ac6052ab87785fb119d) and then expanding to support it in each other file.

Except:

* This improvement never made it into a Mana client release since it happened after 0.6.1.
* It expects a single `settings.xml` at the root, and all files to be included from there. Currently, The Mana World obviously does not have such a file.

So, I'll need to convince you to add a `settings.xml` to your data, or to code some kind of compatibility fallback. Example `settings.xml` can be found at:

* Source of Tales: https://github.com/tales/sourceoftales/blob/master/settings.xml
* manaserv example: https://github.com/mana/manaserv/blob/master/example/settings.xml

**Comment by bjorn** [comment]
I also see the support is slightly different. In Mana client, the `include` tag takes a `file` attribute with a relative file path, whereas in ManaPlus, the `include` tag takes a `name` attribute, with an absolute file path. Well, not that hard to add support for absolute include paths I guess.

**Comment by bjorn** [comment]
Alright, after d86a1df562e00a6e930683534b9d001f45a951ff, my characters now look like this:

![image](https://github.com/mana/mana/assets/531764/1b129702-4a9a-45ed-b52c-b71529d358d8)

I see at least two remaining issues:

* What happened to the faces? Apparently they are no longer part of the base character.
* The hair does not have the right color. Not very surprising, because TMW has no `hair.xml` anymore. Did this turn into `itemcolors.xml`? Though I tried loading that instead of `hair.xml` and it didn't immediately fix it.

**Comment by bjorn** [comment]
Adjusted title, because now that we can manage to get into the game, we can see that heads are missing there as well.

![image](https://github.com/mana/mana/assets/531764/2421867b-ccc1-4add-a90f-a1bca8ebe728)

@pazkero Any information about how we could fix the heads?

**Comment by bjorn** [comment]
Issue moved to https://git.themanaworld.org/mana/mana/-/issues/43.
