### ISSUE TITLE
Unknown packet 0x226 after connecting to the map server

### ISSUE THREAD

**Issue by bjorn** [mana/mana#44]
When trying to play TMW, after choosing the character the client exits with the error:
```
Error: Zero length packet received. Exiting.
```
This is packet 0x226, which has length 0 because it is unknown. In ManaPlus, this packet is known as SMSG_MAP_MASK and we'll need to handle this gracefully.

**Comment by pazkero** [comment]
SMSG_MAP_MASK ─ controls the `Mask` attribute from the tmx map file. Bitmasked value. Server will usually send "1" (render the map). Value can likely be ignored for now, very few maps use it (i.e. The Final Showdown quest maps only).

So e.g. if SMSG_MAP_MASK = 3, then it'll render the map ("1") and any layer with Mask = 2. If it was SMSG_MAP_MASK = 5,  then it would render the map ("1") and any layer with Mask = 4. Needless to say, layers with Mask = 2 won't be rendered if SMSG_MAP_MASK = 5.

I assume the packet is sending the actual map mask; I don't know the length either.

**Comment by bjorn** [comment]
@pazkero Ah, thanks for providing some context!
